### ISSUE TITLE
unable to save values

### ISSUE THREAD

**Issue by flucas1** [edk2-porting/edk2-rk3588#107] opened 2023-12-07 00:24 UTC
I have an orange pi 5 plus,
I boot via an SD card, but when trying to change the optiosn in the menu, and press F10, and then reboot the changes are not persisting.

**Comment by lyazide** [comment] 2023-12-23 16:58
Same for me. Did you find a solution

**Comment by mariobalanica** [comment] 2024-01-05 19:32
Duplicate of #94 .

**Closed by mariobalanica** 2024-01-05 19:32 UTC
Labels: type/duplicate
